# Generated by Django 4.1.7 on 2023-04-28 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Eighth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Fifth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='First',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Forth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Nineth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Second',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Seventh',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Sixth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Tenth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Third',
        ),
        migrations.RemoveField(
            model_name='device',
            name='upadte_time',
        ),
        migrations.CreateModel(
            name='DeviceVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Andriod', 'Andriod'), ('iPhone&iPad', 'iPhone&iPad'), ('Mac', 'Mac'), ('Routers', 'Routers'), ('Pc', 'Pc'), ('Windows', 'Windows')], default='', max_length=200)),
                ('user_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5)])),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vpn.vpnlist')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='vpn',
            field=models.ManyToManyField(to='vpn.devicevpn'),
        ),
    ]
