# Generated by Django 4.1.7 on 2023-03-29 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparision',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('vpn', models.CharField(max_length=1000, unique=True)),
                ('comparison_description', models.TextField()),
                ('moneybackguarantee', models.CharField(default='', max_length=1000)),
                ('servers_or_countries', models.CharField(default='', max_length=1000)),
                ('killswitch', models.CharField(default='', max_length=1000)),
                ('number_of_device_or_licence', models.IntegerField(default=0)),
                ('mobile', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('Ques_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='remark',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('remarks', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('vpn_name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='logo',
            field=models.ImageField(default='', upload_to='archivos'),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='offer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='riben_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='website_url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[['Overall Best Vpn of 2023', 'Overall Best Vpn of 2023']], max_length=100, unique=True)),
                ('upadte_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_5th_set', to='vpn.vpnlist')),
                ('First', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_1st_set', to='vpn.vpnlist')),
                ('Forth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_4th_set', to='vpn.vpnlist')),
                ('Second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2nd_set', to='vpn.vpnlist')),
                ('Seventh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_7th_set', to='vpn.vpnlist')),
                ('Sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_6th_set', to='vpn.vpnlist')),
                ('Third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_3rd_set', to='vpn.vpnlist')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[['🇦🇼', 'Aruba'], ['🇦🇫', 'Afghanistan'], ['🇦🇴', 'Angola'], ['🇦🇮', 'Anguilla'], ['🇦🇽', 'Åland Islands'], ['🇦🇱', 'Albania'], ['🇦🇩', 'Andorra'], ['🇦🇪', 'United Arab Emirates'], ['🇦🇷', 'Argentina'], ['🇦🇲', 'Armenia'], ['🇦🇸', 'American Samoa'], ['🇦🇶', 'Antarctica'], ['🇹🇫', 'French Southern Territories'], ['🇦🇬', 'Antigua and Barbuda'], ['🇦🇺', 'Australia'], ['🇦🇹', 'Austria'], ['🇦🇿', 'Azerbaijan'], ['🇧🇮', 'Burundi'], ['🇧🇪', 'Belgium'], ['🇧🇯', 'Benin'], ['🇧🇶', 'Bonaire, Sint Eustatius and Saba'], ['🇧🇫', 'Burkina Faso'], ['🇧🇩', 'Bangladesh'], ['🇧🇬', 'Bulgaria'], ['🇧🇭', 'Bahrain'], ['🇧🇸', 'Bahamas'], ['🇧🇦', 'Bosnia and Herzegovina'], ['🇧🇱', 'Saint Barthélemy'], ['🇧🇾', 'Belarus'], ['🇧🇿', 'Belize'], ['🇧🇲', 'Bermuda'], ['🇧🇴', 'Bolivia, Plurinational State of'], ['🇧🇷', 'Brazil'], ['🇧🇧', 'Barbados'], ['🇧🇳', 'Brunei Darussalam'], ['🇧🇹', 'Bhutan'], ['🇧🇻', 'Bouvet Island'], ['🇧🇼', 'Botswana'], ['🇨🇫', 'Central African Republic'], ['🇨🇦', 'Canada'], ['🇨🇨', 'Cocos (Keeling) Islands'], ['🇨🇭', 'Switzerland'], ['🇨🇱', 'Chile'], ['🇨🇳', 'China'], ['🇨🇮', "Côte d'Ivoire"], ['🇨🇲', 'Cameroon'], ['🇨🇩', 'Congo, The Democratic Republic of the'], ['🇨🇬', 'Congo'], ['🇨🇰', 'Cook Islands'], ['🇨🇴', 'Colombia'], ['🇰🇲', 'Comoros'], ['🇨🇻', 'Cabo Verde'], ['🇨🇷', 'Costa Rica'], ['🇨🇺', 'Cuba'], ['🇨🇼', 'Curaçao'], ['🇨🇽', 'Christmas Island'], ['🇰🇾', 'Cayman Islands'], ['🇨🇾', 'Cyprus'], ['🇨🇿', 'Czechia'], ['🇩🇪', 'Germany'], ['🇩🇯', 'Djibouti'], ['🇩🇲', 'Dominica'], ['🇩🇰', 'Denmark'], ['🇩🇴', 'Dominican Republic'], ['🇩🇿', 'Algeria'], ['🇪🇨', 'Ecuador'], ['🇪🇬', 'Egypt'], ['🇪🇷', 'Eritrea'], ['🇪🇭', 'Western Sahara'], ['🇪🇸', 'Spain'], ['🇪🇪', 'Estonia'], ['🇪🇹', 'Ethiopia'], ['🇫🇮', 'Finland'], ['🇫🇯', 'Fiji'], ['🇫🇰', 'Falkland Islands (Malvinas)'], ['🇫🇷', 'France'], ['🇫🇴', 'Faroe Islands'], ['🇫🇲', 'Micronesia, Federated States of'], ['🇬🇦', 'Gabon'], ['🇬🇧', 'United Kingdom'], ['🇬🇪', 'Georgia'], ['🇬🇬', 'Guernsey'], ['🇬🇭', 'Ghana'], ['🇬🇮', 'Gibraltar'], ['🇬🇳', 'Guinea'], ['🇬🇵', 'Guadeloupe'], ['🇬🇲', 'Gambia'], ['🇬🇼', 'Guinea-Bissau'], ['🇬🇶', 'Equatorial Guinea'], ['🇬🇷', 'Greece'], ['🇬🇩', 'Grenada'], ['🇬🇱', 'Greenland'], ['🇬🇹', 'Guatemala'], ['🇬🇫', 'French Guiana'], ['🇬🇺', 'Guam'], ['🇬🇾', 'Guyana'], ['🇭🇰', 'Hong Kong'], ['🇭🇲', 'Heard Island and McDonald Islands'], ['🇭🇳', 'Honduras'], ['🇭🇷', 'Croatia'], ['🇭🇹', 'Haiti'], ['🇭🇺', 'Hungary'], ['🇮🇩', 'Indonesia'], ['🇮🇲', 'Isle of Man'], ['🇮🇳', 'India'], ['🇮🇴', 'British Indian Ocean Territory'], ['🇮🇪', 'Ireland'], ['🇮🇷', 'Iran, Islamic Republic of'], ['🇮🇶', 'Iraq'], ['🇮🇸', 'Iceland'], ['🇮🇱', 'Israel'], ['🇮🇹', 'Italy'], ['🇯🇲', 'Jamaica'], ['🇯🇪', 'Jersey'], ['🇯🇴', 'Jordan'], ['🇯🇵', 'Japan'], ['🇰🇿', 'Kazakhstan'], ['🇰🇪', 'Kenya'], ['🇰🇬', 'Kyrgyzstan'], ['🇰🇭', 'Cambodia'], ['🇰🇮', 'Kiribati'], ['🇰🇳', 'Saint Kitts and Nevis'], ['🇰🇷', 'Korea, Republic of'], ['🇰🇼', 'Kuwait'], ['🇱🇦', "Lao People's Democratic Republic"], ['🇱🇧', 'Lebanon'], ['🇱🇷', 'Liberia'], ['🇱🇾', 'Libya'], ['🇱🇨', 'Saint Lucia'], ['🇱🇮', 'Liechtenstein'], ['🇱🇰', 'Sri Lanka'], ['🇱🇸', 'Lesotho'], ['🇱🇹', 'Lithuania'], ['🇱🇺', 'Luxembourg'], ['🇱🇻', 'Latvia'], ['🇲🇴', 'Macao'], ['🇲🇫', 'Saint Martin (French part)'], ['🇲🇦', 'Morocco'], ['🇲🇨', 'Monaco'], ['🇲🇩', 'Moldova, Republic of'], ['🇲🇬', 'Madagascar'], ['🇲🇻', 'Maldives'], ['🇲🇽', 'Mexico'], ['🇲🇭', 'Marshall Islands'], ['🇲🇰', 'North Macedonia'], ['🇲🇱', 'Mali'], ['🇲🇹', 'Malta'], ['🇲🇲', 'Myanmar'], ['🇲🇪', 'Montenegro'], ['🇲🇳', 'Mongolia'], ['🇲🇵', 'Northern Mariana Islands'], ['🇲🇿', 'Mozambique'], ['🇲🇷', 'Mauritania'], ['🇲🇸', 'Montserrat'], ['🇲🇶', 'Martinique'], ['🇲🇺', 'Mauritius'], ['🇲🇼', 'Malawi'], ['🇲🇾', 'Malaysia'], ['🇾🇹', 'Mayotte'], ['🇳🇦', 'Namibia'], ['🇳🇨', 'New Caledonia'], ['🇳🇪', 'Niger'], ['🇳🇫', 'Norfolk Island'], ['🇳🇬', 'Nigeria'], ['🇳🇮', 'Nicaragua'], ['🇳🇺', 'Niue'], ['🇳🇱', 'Netherlands'], ['🇳🇴', 'Norway'], ['🇳🇵', 'Nepal'], ['🇳🇷', 'Nauru'], ['🇳🇿', 'New Zealand'], ['🇴🇲', 'Oman'], ['🇵🇰', 'Pakistan'], ['🇵🇦', 'Panama'], ['🇵🇳', 'Pitcairn'], ['🇵🇪', 'Peru'], ['🇵🇭', 'Philippines'], ['🇵🇼', 'Palau'], ['🇵🇬', 'Papua New Guinea'], ['🇵🇱', 'Poland'], ['🇵🇷', 'Puerto Rico'], ['🇰🇵', "Korea, Democratic People's Republic of"], ['🇵🇹', 'Portugal'], ['🇵🇾', 'Paraguay'], ['🇵🇸', 'Palestine, State of'], ['🇵🇫', 'French Polynesia'], ['🇶🇦', 'Qatar'], ['🇷🇪', 'Réunion'], ['🇷🇴', 'Romania'], ['🇷🇺', 'Russian Federation'], ['🇷🇼', 'Rwanda'], ['🇸🇦', 'Saudi Arabia'], ['🇸🇩', 'Sudan'], ['🇸🇳', 'Senegal'], ['🇸🇬', 'Singapore'], ['🇬🇸', 'South Georgia and the South Sandwich Islands'], ['🇸🇭', 'Saint Helena, Ascension and Tristan da Cunha'], ['🇸🇯', 'Svalbard and Jan Mayen'], ['🇸🇧', 'Solomon Islands'], ['🇸🇱', 'Sierra Leone'], ['🇸🇻', 'El Salvador'], ['🇸🇲', 'San Marino'], ['🇸🇴', 'Somalia'], ['🇵🇲', 'Saint Pierre and Miquelon'], ['🇷🇸', 'Serbia'], ['🇸🇸', 'South Sudan'], ['🇸🇹', 'Sao Tome and Principe'], ['🇸🇷', 'Suriname'], ['🇸🇰', 'Slovakia'], ['🇸🇮', 'Slovenia'], ['🇸🇪', 'Sweden'], ['🇸🇿', 'Eswatini'], ['🇸🇽', 'Sint Maarten (Dutch part)'], ['🇸🇨', 'Seychelles'], ['🇸🇾', 'Syrian Arab Republic'], ['🇹🇨', 'Turks and Caicos Islands'], ['🇹🇩', 'Chad'], ['🇹🇬', 'Togo'], ['🇹🇭', 'Thailand'], ['🇹🇯', 'Tajikistan'], ['🇹🇰', 'Tokelau'], ['🇹🇲', 'Turkmenistan'], ['🇹🇱', 'Timor-Leste'], ['🇹🇴', 'Tonga'], ['🇹🇹', 'Trinidad and Tobago'], ['🇹🇳', 'Tunisia'], ['🇹🇷', 'Turkey'], ['🇹🇻', 'Tuvalu'], ['🇹🇼', 'Taiwan, Province of China'], ['🇹🇿', 'Tanzania, United Republic of'], ['🇺🇬', 'Uganda'], ['🇺🇦', 'Ukraine'], ['🇺🇲', 'United States Minor Outlying Islands'], ['🇺🇾', 'Uruguay'], ['🇺🇸', 'United States'], ['🇺🇿', 'Uzbekistan'], ['🇻🇦', 'Holy See (Vatican City State)'], ['🇻🇨', 'Saint Vincent and the Grenadines'], ['🇻🇪', 'Venezuela, Bolivarian Republic of'], ['🇻🇬', 'Virgin Islands, British'], ['🇻🇮', 'Virgin Islands, U.S.'], ['🇻🇳', 'Viet Nam'], ['🇻🇺', 'Vanuatu'], ['🇼🇫', 'Wallis and Futuna'], ['🇼🇸', 'Samoa'], ['🇾🇪', 'Yemen'], ['🇿🇦', 'South Africa'], ['🇿🇲', 'Zambia'], ['🇿🇼', 'Zimbabwe']], max_length=100, unique=True)),
                ('upadte_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_5_set', to='vpn.vpnlist')),
                ('First', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_1_set', to='vpn.vpnlist')),
                ('Forth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_4_set', to='vpn.vpnlist')),
                ('Second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2_set', to='vpn.vpnlist')),
                ('Seventh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_7_set', to='vpn.vpnlist')),
                ('Sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_6_set', to='vpn.vpnlist')),
                ('Third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_3_set', to='vpn.vpnlist')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('Andriod', 'Andriod'), ('iPhone&iPad', 'iPhone&iPad'), ('Mac', 'Mac'), ('Routers', 'Routers'), ('Pc', 'Pc'), ('Windows', 'Windows')], max_length=100, unique=True)),
                ('upadte_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Fifth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_fifth_set', to='vpn.vpnlist')),
                ('First', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_first_set', to='vpn.vpnlist')),
                ('Forth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_forth_set', to='vpn.vpnlist')),
                ('Second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_second_set', to='vpn.vpnlist')),
                ('Seventh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_seventh_set', to='vpn.vpnlist')),
                ('Sixth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_sexth_set', to='vpn.vpnlist')),
                ('Third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_third_set', to='vpn.vpnlist')),
            ],
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='Comparision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vpn.comparision'),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vpn.remark'),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification',
            field=models.ManyToManyField(to='vpn.specification'),
        ),
    ]
