# Generated by Django 4.1.7 on 2023-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlist',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
