# Generated by Django 4.1.7 on 2023-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_comparision_faq_feature_form_remark_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlist',
            name='icon',
            field=models.ImageField(default='', upload_to='archivos'),
        ),
    ]
