# Generated by Django 4.1.7 on 2023-03-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_alter_comparision_id_alter_device_id_alter_form_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(default='', unique=True)),
                ('Answer', models.TextField(default='')),
            ],
        ),
    ]
