# Generated by Django 4.1.7 on 2023-04-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_vpnlist_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparision',
            name='ChargePerMonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='Comparision',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='vpn.comparision'),
        ),
    ]
