# Generated by Django 4.1.7 on 2023-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_vpnlist_rating_vpnlist_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification',
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
