# Generated by Django 4.1.7 on 2023-04-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_comparision_chargepermonth_alter_vpnlist_comparision'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Eighth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_eighth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Nineth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_nineth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Tenth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_tenth_set', to='vpn.vpnlist'),
        ),
    ]
