# Generated by Django 4.1.7 on 2023-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Privacy', 'Privacy'), ('Speed', 'Speed'), ('security', 'Security'), ('Newbies', 'Newbies')], default=1, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='feature',
            field=models.ManyToManyField(to='vpn.feature'),
        ),
    ]
