# Generated by Django 4.1.7 on 2023-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_remove_vpnlist_rating_remove_vpnlist_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlist',
            name='offer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='rating_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
