# Generated by Django 4.1.7 on 2023-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_device_eighth_device_nineth_device_tenth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Owner', max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('Facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('Twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('Youtube', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
