# Generated by Django 4.1.7 on 2023-03-18 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_vpnlist_offer_vpnlist_rating_vpnlist_rating_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlist',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
