# Generated by Django 4.1.7 on 2023-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_ownercontactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercontactdetails',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('user1', 'user1'), ('user2', 'user2')], default='', max_length=100, unique=True),
        ),
    ]
