# Generated by Django 4.1.7 on 2023-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_alter_vpnlist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnlist',
            name='website_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
