# Generated by Django 4.1.7 on 2023-03-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_vpnlist_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnlist',
            old_name='rating_type',
            new_name='rating_comment',
        ),
    ]
