# Generated by Django 4.1.7 on 2023-04-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_alter_comparision_killswitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Eighth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_eighth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Nineth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_nineth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Tenth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_tenth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Eighth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2eighth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Nineth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2nineth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Tenth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2tenth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_fifth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_first_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_forth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_second_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_seventh_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_sexth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten1_third_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2fifth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2first_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2forth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2second_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2seventh_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2sexth_set', to='vpn.vpnlist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2third_set', to='vpn.vpnlist'),
        ),
    ]
