# Generated by Django 4.1.7 on 2023-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_location_eighth_location_nineth_location_tenth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'admin'), ('user1', 'user1'), ('user2', 'user2')], default='', max_length=200, unique=True)),
                ('last_changed_date', models.DateTimeField()),
            ],
        ),
    ]
