# Generated by Django 4.1.7 on 2023-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_lastupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='ChargePerMonth',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
