# Generated by Django 4.1.7 on 2023-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_device_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('First', models.CharField(max_length=200)),
                ('Second', models.CharField(max_length=200)),
                ('Third', models.CharField(max_length=200)),
                ('Fourth', models.CharField(max_length=200)),
                ('Fivth', models.CharField(max_length=200)),
                ('Sixth', models.CharField(max_length=200)),
                ('Seventh', models.CharField(max_length=200)),
                ('Eighth', models.CharField(max_length=200)),
                ('Ninth', models.CharField(max_length=200)),
                ('Tenth', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
