# Generated by Django 4.1.7 on 2023-05-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_devicevpn_ranking_alter_location_name'),
        ('vpn', '0011_alter_comparision_chargepermonth'),
    ]

    operations = [
    ]
