# Generated by Django 4.1.7 on 2023-03-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_topten_alter_service_name_alter_vpnlist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTenList',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('First', models.CharField(max_length=200)),
                ('Second', models.CharField(max_length=200)),
                ('Third', models.CharField(max_length=200)),
                ('Fourth', models.CharField(max_length=200)),
                ('Fivth', models.CharField(max_length=200)),
                ('Sixth', models.CharField(max_length=200)),
                ('Seventh', models.CharField(max_length=200)),
                ('Eighth', models.CharField(max_length=200)),
                ('Ninth', models.CharField(max_length=200)),
                ('Tenth', models.CharField(max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.location')),
            ],
        ),
        migrations.DeleteModel(
            name='TopTen',
        ),
    ]
