# Generated by Django 4.1.7 on 2023-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0013_alter_toptenlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptenlist',
            name='type',
            field=models.CharField(blank=True, choices=[('location', 1), ('device', 2), ('service', 3)], max_length=200, null=True),
        ),
    ]
