# Generated by Django 4.1.7 on 2023-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0015_location_eighth_rating_location_first_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('china', 'china'), ('unitedState', 'unitedState'), ('india', 'india'), ('australia', 'australia'), ('burundi', 'burundi'), ('unitedArabEmirates', 'unitedArabEmirates')], max_length=200, unique=True),
        ),
    ]
