# Generated by Django 4.1.7 on 2023-03-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0015_all_avilable_filter_remove_toptenlist_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
        migrations.AlterField(
            model_name='toptenlist',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
    ]
