# Generated by Django 4.1.7 on 2023-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0016_alter_device_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Type',
        ),
        migrations.DeleteModel(
            name='All_avilable_filter',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TopTenList',
        ),
    ]
