# Generated by Django 4.1.7 on 2023-05-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0018_alter_device_first_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Fivth_rating',
            new_name='Fifth_rating',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='Forth',
            new_name='Fourth',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Fivth_rating',
            new_name='Fifth_rating',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Forth',
            new_name='Fourth',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Fivth_rating',
            new_name='Fifth_rating',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Forth',
            new_name='Fourth',
        ),
        migrations.AddField(
            model_name='device',
            name='Eighth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Fifth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Fourth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Ninth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Second_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Seventh_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Sixth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Tenth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='Third_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Eighth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Fifth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='First_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Fourth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Ninth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Second_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Seventh_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Sixth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Tenth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Third_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Eighth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Fifth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Nineth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Second_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Seventh_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Sixth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Tenth_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='Third_remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='fourth_remark',
            field=models.CharField(default='', max_length=200),
        ),
    ]
