# Generated by Django 4.1.7 on 2023-03-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0019_toptenlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptenlist',
            name='Eighth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Fivth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Fourth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Ninth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Second',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Seventh',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Sixth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Tenth',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='Third',
        ),
        migrations.AlterField(
            model_name='toptenlist',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.vpnlist'),
        ),
    ]
