# Generated by Django 4.1.7 on 2023-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0019_rename_fivth_rating_device_fifth_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Eighth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Fifth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='First_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Fourth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Ninth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Second_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Seventh_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Sixth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Tenth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='Third_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Eighth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Fifth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='First_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Fourth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Ninth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Second_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Seventh_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Sixth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Tenth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Third_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Eighth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Fifth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Nineth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Second_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Seventh_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Sixth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Tenth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Third_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='fourth_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
    ]
