# Generated by Django 4.1.7 on 2023-03-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0020_remove_toptenlist_eighth_remove_toptenlist_fivth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toptenlist',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='First',
        ),
    ]
