# Generated by Django 4.1.7 on 2023-05-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0020_alter_device_eighth_remark_alter_device_fifth_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Fourth',
            new_name='Forth',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Fourth',
            new_name='Forth',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Fourth',
            new_name='Forth',
        ),
    ]
