# Generated by Django 4.1.7 on 2023-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0021_rename_fourth_device_forth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='First_remark',
            field=models.CharField(default='Good', max_length=200),
        ),
    ]
