# Generated by Django 4.1.7 on 2023-03-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0021_rename_type_toptenlist_type_remove_toptenlist_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptenlist',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
    ]
