# Generated by Django 4.1.7 on 2023-03-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0024_toptenlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptenlist',
            name='type',
        ),
        migrations.AddField(
            model_name='toptenlist',
            name='first',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vpn.vpnlist'),
        ),
    ]
