# Generated by Django 4.1.7 on 2023-03-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0029_toptenlist_first_toptenlist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptenlist',
            name='first',
        ),
        migrations.RemoveField(
            model_name='toptenlist',
            name='type',
        ),
    ]
