# Generated by Django 4.1.7 on 2023-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0031_toptenlist_first_toptenlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_avilable_filter',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
