# Generated by Django 4.1.7 on 2023-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0032_alter_all_avilable_filter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlist',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
