# Generated by Django 4.1.7 on 2023-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0035_remove_toptenlist_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopTenList',
        ),
    ]
