# Generated by Django 4.1.7 on 2023-03-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0037_toptenlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopTenList',
        ),
    ]
