# Generated by Django 4.1.7 on 2023-03-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0040_top_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_ten',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.vpnlist'),
        ),
    ]
