# Generated by Django 4.1.7 on 2023-03-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0043_alter_top_ten_eighth_alter_top_ten_fifth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='rating_comment',
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='logo',
            field=models.ImageField(default=None, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='website_url',
            field=models.URLField(default=None, max_length=1000),
        ),
    ]
