# Generated by Django 4.1.7 on 2023-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0045_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
