# Generated by Django 4.1.7 on 2023-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0050_devices_delete_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
