# Generated by Django 4.1.7 on 2023-03-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0052_devices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
