# Generated by Django 4.1.7 on 2023-03-18 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0055_rename_device_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter')),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
