# Generated by Django 4.1.7 on 2023-03-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0056_device_delete_devices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
