# Generated by Django 4.1.7 on 2023-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0061_service_location_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
