# Generated by Django 4.1.7 on 2023-03-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0064_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
    ]
