# Generated by Django 4.1.7 on 2023-03-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0071_alter_service_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('id', 'name')},
        ),
    ]
