# Generated by Django 4.1.7 on 2023-03-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0072_alter_device_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter', unique=True),
        ),
    ]
