# Generated by Django 4.1.7 on 2023-03-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0073_alter_location_unique_together_alter_location_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.all_avilable_filter'),
        ),
    ]
