# Generated by Django 4.1.7 on 2023-03-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0075_top_ten_unique_top_ten'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='top_ten',
            name='unique_top_ten',
        ),
    ]
