# Generated by Django 4.1.7 on 2023-03-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0076_remove_top_ten_unique_top_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_ten',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vpn.all_avilable_filter'),
        ),
    ]
