# Generated by Django 4.1.7 on 2023-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0077_alter_top_ten_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_ten',
            name='upadte_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
