# Generated by Django 4.1.7 on 2023-03-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0078_top_ten_upadte_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('Ques_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
