# Generated by Django 4.1.7 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0079_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnlist',
            old_name='specification',
            new_name='specification1',
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='specification5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
