# Generated by Django 4.1.7 on 2023-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0080_rename_specification_vpnlist_specification1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification1',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification2',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification3',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification4',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification5',
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='Device',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='coutries_allowed',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='killswitch',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='moneybackguarantee',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='number_of_device_or_licence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='logo',
            field=models.ImageField(default='', upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='website_url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='Specification',
            field=models.ManyToManyField(to='vpn.specification'),
        ),
    ]
