# Generated by Django 4.1.7 on 2023-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0082_specification_vpn_name_alter_specification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='vpn_name',
            field=models.CharField(max_length=1000),
        ),
    ]
