# Generated by Django 4.1.7 on 2023-03-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0084_rename_specification_vpnlist_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification',
        ),
    ]
