# Generated by Django 4.1.7 on 2023-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0086_vpnlist_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='specification',
        ),
    ]
