# Generated by Django 4.1.7 on 2023-03-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0088_vpnlist_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_ten',
            name='type',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='vpn.all_avilable_filter'),
        ),
    ]
