# Generated by Django 4.1.7 on 2023-03-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0089_alter_top_ten_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('remark', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='riben_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='vpnlist',
            name='remarks',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vpn.remarks'),
        ),
    ]
