# Generated by Django 4.1.7 on 2023-03-23 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0093_comparision_remove_vpnlist_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vpn.remark'),
        ),
    ]
