# Generated by Django 4.1.7 on 2023-03-26 09:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0094_alter_vpnlist_rating_alter_vpnlist_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_ten',
            name='vpn_in_order',
            field=django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
