# Generated by Django 4.1.7 on 2023-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0096_remove_top_ten_vpn_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(choices=[('Andriod', 'Andriod'), ('iPhone&iPad', 'iPhone&iPad'), ('Mac', 'Mac'), ('Routers', 'Routers'), ('Pc', 'Pc'), ('Windows', 'Windows')], max_length=100),
        ),
    ]
