# Generated by Django 4.1.7 on 2023-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0099_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[['Overall Best Vpn of 2023', 'Overall Best Vpn of 2023']], max_length=100, unique=True),
        ),
    ]
