# Generated by Django 4.1.7 on 2023-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0101_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(choices=[['Zimbabwe', 'Zimbabwe']], max_length=100, unique=True),
        ),
    ]
