# Generated by Django 4.1.7 on 2023-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0106_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_ten',
            name='type',
        ),
        migrations.AddField(
            model_name='top_ten',
            name='module',
            field=models.CharField(choices=[('Location', 'Location'), ('Device', 'Device')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='top_ten',
            name='selected_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
