# Generated by Django 4.1.7 on 2023-03-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0107_remove_top_ten_type_top_ten_module_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_avilable_filter',
        ),
        migrations.AddField(
            model_name='device',
            name='Fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_fifth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_first_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_forth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_second_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_seventh_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_sexth_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='Third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_third_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='device',
            name='upadte_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Top_ten',
        ),
    ]
