# Generated by Django 4.1.7 on 2023-03-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0108_delete_all_avilable_filter_device_fifth_device_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_5_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_1_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_4_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_7_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_6_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='Third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_3_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='location',
            name='upadte_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
