# Generated by Django 4.1.7 on 2023-03-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0112_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_5th_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='First',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_1st_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_4th_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_2nd_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_7th_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_6th_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='Third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_ten_3rd_set', to='vpn.vpnlist'),
        ),
        migrations.AddField(
            model_name='service',
            name='upadte_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
